language: haskell

ghc:
  - 7.6
  - 7.8

env:
  - lower_bound_dependencies=0
  
install:
  - if [ $lower_bound_dependencies -eq 1 ];
    then
      cabal install "mtl == 2.2.*";
      cabal install "transformers == 0.4.*";
    fi;
  - cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls

