language: haskell

ghc:
  - 7.6
  - 7.8

env:
  - mtl=2.0.* transformers=0.2.*
  - mtl=2.1.* transformers=0.3.*
  - mtl=2.2.* transformers=0.4.*
  
install:
  - cabal install "mtl == $mtl"
  - cabal install "transformers == $transformers"
  - cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls

